spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: dev
  mvc:
    servlet:
      load-on-startup: 0
  resources:
    static-locations:
      - classpath:/static/
      - file:///${jk.upload.base-path}

mybatis-plus:
  global-config:
    db-config:
      # 主键策略：自增
      id-type: auto
  # 起别名
  type-aliases-package: com.wang.jk.pojo
  configuration:
    use-generated-keys: true

jk:
  token:
    issuer: mj
    secret: m!j@6[6]6=
    access-token-duration: P1D
    refresh-token-duration: P7D