spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jiakao?serverTimezone=GMT%2B8
    username: root
    password: 020328wang

logging:
  level:
    com.mj.jk: debug

server:
  port: 8080

jk:
  web:
    cors-origins:
      - http://localhost:63342
  upload:
    base-path: F:/jk/
    upload-path: upload/
    image-path: img/
    video-path: video/

